import = ["/home/norte/.config/alacritty/nord.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 2
y = 2

[window.dimensions]
columns = 100
lines = 60
